# Generated by Django 3.0.7 on 2020-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='capacity',
            new_name='cur_capacity',
        ),
        migrations.AddField(
            model_name='business',
            name='max_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
