# Generated by Django 3.0.7 on 2020-07-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
    ]
