# Generated by Django 3.0.7 on 2020-06-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intermediate', '0001_initial'),
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cur_postcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=9)),
                ('favorites', models.ManyToManyField(to='b2b.Business')),
            ],
        ),
    ]
