# Generated by Django 3.0.7 on 2020-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
        ('b2c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cur_postcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='b2b.Business'),
        ),
    ]
