# Generated by Django 3.0.7 on 2020-07-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c', '0002_auto_20200701_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
